import { BadgeDollarSign, CreditCard, Landmark, UserPlus, Users, Wallet } from "lucide-react";

export const dashboardCards = [
  {
    category: "overview",
    title: "Total User",
    value: "24,892",
    valueKey: "total_user",
    icon: Users,
    href: "/users/list-user",
  },
  {
    category: "overview",
    title: "Total IB",
    value: "1,240",
    valueKey: "total_ib",
    icon: Landmark,
    href: "/ib-managment/list-become-ib",
  },
  {
    category: "overview",
    title: "Total Withdrawal",
    value: "$540K",
    valueKey: "total_withdraw",
    valueType: "currency",
    icon: Wallet,
    href: "/report/withdrawal-report",
  },
  {
    category: "overview",
    title: "Total Deposit",
    value: "$1.2M",
    valueKey: "total_deposit",
    valueType: "currency",
    icon: BadgeDollarSign,
    href: "/report/deposit-report",
  },

  // Deposits
  {
    category: "deposits",
    title: "Daily Deposit",
    value: "$12,450",
    valueKey: "daily_deposit",
    valueType: "currency",
    icon: Wallet,
    href: "/report/deposit-report",
  },
  {
    category: "deposits",
    title: "Weekly Deposit",
    value: "$84,320",
    valueKey: "weekly_deposit",
    valueType: "currency",
    icon: CreditCard,
    href: "/report/deposit-report",
  },
  {
    category: "deposits",
    title: "Monthly Deposit",
    value: "$240,000",
    valueKey: "monthly_deposit",
    valueType: "currency",
    icon: Wallet,
    href: "/report/deposit-report",
  },
  {
    category: "deposits",
    title: "Pending Deposit",
    value: "42",
    valueKey: "pending_deposit",
    icon: Wallet,
    href: "/userkyc/new-kyc",
  },

  // Withdrawals
  {
    category: "withdrawals",
    title: "Daily Withdraw",
    value: "$4,250",
    valueKey: "daily_withdraw",
    valueType: "currency",
    icon: Wallet,
    href: "/report/withdrawal-report",
  },
  {
    category: "withdrawals",
    title: "Weekly Withdraw",
    value: "$28,900",
    valueKey: "weekly_withdraw",
    valueType: "currency",
    icon: Wallet,
    href: "/report/withdrawal-report",
  },
  {
    category: "withdrawals",
    title: "Monthly Withdraw",
    value: "$98,000",
    valueKey: "monthly_withdraw",
    valueType: "currency",
    icon: Wallet,
    href: "/report/withdrawal-report",
  },
  {
    category: "withdrawals",
    title: "Pending Withdraw",
    value: "19",
    valueKey: "pending_withdraw",
    icon: Wallet,
    href: "/withdrawal/withdrawal-request",
  },

  // IB
  {
    category: "ib",
    title: "Daily IB Withdraw",
    value: "$1,200",
    icon: Landmark,
    href: "/report/ib-withdrawal-report",
  },
  {
    category: "ib",
    title: "Weekly IB Withdraw",
    value: "$8,400",
    icon: Landmark,
    href: "/report/ib-withdrawal-report",
  },
  {
    category: "ib",
    title: "Monthly IB Withdraw",
    value: "$24,000",
    icon: Landmark,
    href: "/report/ib-withdrawal-report",
  },
  {
    category: "ib",
    title: "Total IB Withdraw",
    value: "$120K",
    icon: BadgeDollarSign,
    href: "/report/ib-withdrawal-report",
  },
  {
    category: "ib",
    title: "Pending IB Request",
    value: "12",
    valueKey: "pending_ib_request",
    icon: Landmark,
    href: "/ib-managment/list-ib-request",
  },

  // Registrations
  {
    category: "registrations",
    title: "Daily Registration",
    value: "182",
    valueKey: "daily_registration",
    icon: UserPlus,
    href: "/users/list-user",
  },
  {
    category: "registrations",
    title: "Monthly Registration",
    value: "4,820",
    valueKey: "monthly_registration",
    icon: Users,
    href: "/users/list-user",
  },

  // MT5
  {
    category: "mt5",
    title: "Daily MT5 ID",
    value: "54",
    valueKey: "daily_mt5_id",
    icon: CreditCard,
    href: "/users/mt5-user-list",
  },
  {
    category: "mt5",
    title: "Monthly MT5 ID",
    value: "1,340",
    valueKey: "monthly_mt5_id",
    icon: CreditCard,
    href: "/users/mt5-user-list",
  },
];
